services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code/fastapi_deploy
    command: uvicorn fastapi_deploy.server:app --host 0.0.0.0 --port 8000